version: "3.9"

services:
  app:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    links:
      - postgres
      - cache
      - kafka
    depends_on:
      - postgres
      - cache
      - kafka

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - config/pg.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - config/redis.env
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "29092:29092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://kafka:9092,INSIDE_PROD://kafka:9093,EXTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,INSIDE_PROD://kafka:9093,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,INSIDE_PROD:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "fio-topic:2:1"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_LOG_DIRS: /kafka/logs
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/broker/kafka-logs:/kafka
      - ./kafka/broker/logs:/logs
      - ./kafka/broker/data:/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./kafka/zoo/data:/data
      - ./kafka/zoo/datalog:/datalog

volumes:
  postgres:
  cache:
    driver: local