db_uri: postgres://postgres:password@postgres/db

redis_uri: host:post
redis_pass: "redis_pass"

kafka:
  brokers: [ "kafka:9091",  "kafka:9092",  "kafka:9093" ]

http_server:
  address: ":8082"
  timeout: 4s
  idle_timeout: 30s